### ISSUE TITLE
 ImportError: No module named vec_to_bpm

### ISSUE THREAD

**Issue by pannous** [nlml/bpm#1]

**Comment by nlml** [comment]
Committed this dependency

**Comment by pannous** [comment]
that was quick ;)

IOError: [Errno 2] No such file or directory: 'Xy_pulse3.dump'

;)

**Comment by nlml** [comment]
These are quite large files that you'll need to create yourself with your own .wavs and the mp3s_to_fft_features.py script (which I also realised I did not include until now :P)
